# Not sure if this color settings is needed
[env]
TERM = "xterm-256color"
[colors]
draw_bold_text_with_bright_colors = true


# Set colors to catppuccin-mocha
[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]


# Curser Settings
[cursor]
blink_interval = 1000
blink_timeout = 90
[cursor.style]
blinking = "Always"


# Font settings - RobotoMonoNerdFont
[font]
size = 14.0
[font.bold]
family = "RobotoMonoNerdFont"
style = "Bold"
[font.bold_italic]
family = "RobotoMonoNerdFont"
style = "Bold Italic"
[font.italic]
family = "RobotoMonoNerdFont"
style = "Italic"
[font.normal]
family = "RobotoMonoNerdFont"
style = "Regular"


# Keybindings
[[keyboard.bindings]]
action = "SearchBackward"
key = "F"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

# Other settings
[scrolling]
multiplier = 5

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 135
lines = 40
