---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks
- Uni Hannover:
  - StudIp:
    - abbr: SI
      href: https://studip.uni-hannover.de/
  - QIS:
    - abbr: QI
      href: https://qis.verwaltung.uni-hannover.de/qisserver/servlet/de.his.servlet.RequestDispatcherServlet?state=user&type=0&category=menu.browse&breadCrumbSource=portal&startpage=portal.vm&chco=y

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.
          href: https://youtube.com/
