---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: SaynaHome

layout:
  Hallo:
    style: row
    columns: 3

hideVersion: true
showStats: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
